Enhancement/skale 3994 extend provision functionality
skalenetwork/node-provisioning pull request #36
Opened 2021-03-22 15:50 UTC by elvisgiv

2021-03-22 16:44 UTC, dmitry-tk requested changes

2021-03-22 16:44 UTC, dmitry-tk commented on bare-metal/README.md
> +restart_vm_file_name=restart_vm
Why the name of the restart script is a variable? 
Why don't just set the static name:`restart_vm`?

2021-03-22 16:44 UTC, dmitry-tk commented on bare-metal/ansible/files/generate_scripts.py
> +        f.write(f'[Unit]\n' \
Use multiline string here

2021-03-22 16:44 UTC, dmitry-tk commented on bare-metal/ansible/files/generate_scripts.py
> +        f.write(f'[Unit]\n' \
Also: it's better to use j2 template here since 99% of this file is static.

2021-03-22 16:44 UTC, dmitry-tk commented on bare-metal/ansible/roles/add_scripts/tasks/main.yaml
> +- name: Copy {{ restart_vm_file_name }}.sh to {{ base_path }}
Remove `restart_vm_file_name` variable, just set default name

2021-03-22 16:44 UTC, dmitry-tk commented on bare-metal/ansible/files/generate_scripts.py
> +        f.write(f'[Unit]\n' \
See example with `docker-compose.yml.j2`

2021-03-22 16:44 UTC, dmitry-tk commented on bare-metal/ansible/run-vms.yaml
> +    - hosts
Put `generate` and `add` roles in one.

2021-03-23 10:19 UTC, dmitry-tk commented
Also: add cleanup for restart VMs

2021-03-23 13:45 UTC, dmitry-tk commented
@elvisgiv 
Add more informative commit messages.

2021-03-24 08:29 UTC, badrogger approved these changes

2021-03-29 10:11 UTC, dmitry-tk commented
@elvisgiv Add template for terraform `tfvars`, update docs.

2021-04-02 14:09 UTC, dmitry-tk approved these changes

2021-04-02 14:09 UTC, merged