Feature/skale 3996 add skale manager deployment
skalenetwork/node-provisioning pull request #38
Opened 2021-04-06 12:00 UTC by dmitry-tk

2021-04-16 15:46 UTC, badrogger requested changes

2021-04-16 15:46 UTC, badrogger commented on skale-nodes/ansible/main.yaml
> -- import_playbook: base.yaml
Looks like debug artifact

2021-04-16 15:46 UTC, badrogger commented on skale-nodes/ansible/roles/deploy_contracts/tasks/ima.yaml
> +    GAS_PRICE: "{{ deploy_gas_price }}"
I think it's better to separate task with empty lines

2021-04-19 08:48 UTC, dmitry-tk commented on skale-nodes/ansible/main.yaml
> -- import_playbook: base.yaml
fixed

2021-04-19 08:58 UTC, badrogger approved these changes

2021-04-19 13:25 UTC, merged